### PR TITLE
Adding getCohortDefinitionSetFromPackage function

### PR DESCRIPTION
**Pull request by schuemie**
For convenience, I added a function that creates a cohort definition set using the legacy approach to embedding cohort definitions in a package.

I haven't yet added a test, but that could be done by embedding cohorts in this package (CohortGenerator). I have tested it in other packages.

### CODE REVIEW

**Comment by anthonysena** [comment]
Thanks @schuemie for this addition! I'm thinking about this new function in the context of the current [saveCohortDefinitionSet](https://github.com/OHDSI/CohortGenerator/blob/develop/R/ExportSave.R#L97) and had a few thoughts:

- The function you added `getCohortDefinitionSetFromPackage` is a specific form of a more general function (yet to be coded) called `getCohortDefinitionSet` where the root path should be `system.file(fileName, package = packageName)`. 
- I'd like to have `getCohortDefinitionSet` have a similar signature to `saveCohortDefinitionSet` to allow for the same type of get/save options for the user. `getCohortDefinitionSetFromPackage` would then call `getCohortDefinitionSet` with the current standard of storing cohorts in a study package as the defaults.

Let me know what you think about these ideas and if you agree, I can work out the changes on this branch.

**Comment by schuemie** [comment]
Ah sorry, I didn't see `saveCohortDefinitionSet`. One thing to consider is that the function I wrote is specifically aimed at loading a cohort definition set from an installed package (using `system.file`), whereas a function to save a set must always save to a not-yet-built package (saving to an `inst` folder). So at least they cannot be completely symmetrical by default in that sense, if the default for the load function is to load from an installed package. I'm not sure whether that is a big issue, but it will be confusing to users if we're not careful.

**Comment by anthonysena** [comment]
@schuemie - first, I apologize as I did a force push of the "develop" branch since I made an error when merging in the v0.2.0 changes into master. Please delete your local `from_package` branch and pull again from this branch and you should get the change.

Next, I've added some **untested code** in this branch to try and provide a start to the `getCohortDefinitionSet()` function [here](https://github.com/OHDSI/CohortGenerator/pull/3/files#diff-930d357c1494809618b5f048b3ee7a71a286717fff6787d0e0172aeaa2dd1b67R94-R154) and I've preserved your `getCohortDefintionSetFromPackage()` function for comparison [here](https://github.com/OHDSI/CohortGenerator/pull/3/files#diff-930d357c1494809618b5f048b3ee7a71a286717fff6787d0e0172aeaa2dd1b67R28-R54). I stopped here since I wanted to get your opinions on a few thoughts I had as I was authoring the new function:

- I've tried to stay close to the function signature of `saveCohortDefintionSet` and as you mentioned, they won't be symmetrical.  As a result, you'll see they are close with the additions of: `packageName` and `warnOnMissingJson`. The idea was that you can read the cohortDefintionSet from a `packageName` with the `settingsFolder` and `settingsFileName`. `warnOnMissingJson` will allow for a warning if a cohort JSON file is not found; this is yet to be implemented. The other parameters (i.e. `sqlFolder`) provide the same defaults as `getCohortDefintionSetFromPackage()`. My intent is to making calling `getCohortDefinitionSet()` similar to your `getCohortDefinitionSetFromPackage()` in that you need only specify the `settingsFolder`, `settingsFileName` and `packageName` and they will work in the same way (or at least that is my intent).
- How strict should we be with the `cohortId` and `cohortName` fields in the settings file? At the moment, I stopped short of mandating `getCohortDefinitionSet()` require `cohortId` and `cohortName` since I wasn't sure if other studies may have settings files with `id` and `name` that may want to use CohortGenerator but may not want to change the settings files. Also, please ignore the line to add the `atlasId` to the cohortDefintionSet if it is not present after reading the settings file (I'll take that out). Personally I'd want to require `cohortId` and `cohortName` exist in the settings and then pass all columns found in the settings file, along with the JSON/SQL as the resulting cohortDefinitionSet.

**Comment by schuemie** [comment]
I think this looks good. Some minor comments:
1. I'm unclear why there's a separate `settingsFolder` and `settingsFileName `, instead of just a single path to the settings file. There is no other file in the settings folder we're interested in, right?

2. I would already check in the `getPath()` function whether the file exists, for the following reasons: (a) R throws crappy error messages if you try to read from a non-existing file that will not tell you the file does not exist, nor what its name is, and (b) `system.file()` returns an empty string if the file does not exist, so later on it will be harder to throw an error referencing the name of the missing file. 

I'm perfectly fine requiring `cohortId` and `cohortName` as fields in the settings file.

**Comment by anthonysena** [comment]
> I'm unclear why there's a separate settingsFolder and settingsFileName , instead of just a single path to the settings file. There is no other file in the settings folder we're interested in, right?

Correct - I am unsure why I broke that into 2 parameters. I'll revise both get/save functions to simply use a settingsFile that will include the folder.

> I would already check in the getPath() function whether the file exists, for the following reasons: (a) R throws crappy error messages if you try to read from a non-existing file that will not tell you the file does not exist, nor what its name is, and (b) system.file() returns an empty string if the file does not exist, so later on it will be harder to throw an error referencing the name of the missing file.

Agreed - I'll add that. I thought that by using the `mustWork=TRUE` parameter for system.file() it would prevent reading a file that does not exist but the error will still be uninformative. 

> I'm perfectly fine requiring cohortId and cohortName as fields in the settings file.

Great - I'll revise the function based on the feedback above. Thanks!

**Comment by anthonysena** [comment]
@schuemie I've updated this branch with a large number of changes so apologies there. The focus of the branch remains on the `getCohortDefinitionSet()` function which for the legacy cohort storage should work by calling:

```r
getCohortDefinitionSet(packageName = "SomePackage")
```

The function supports some other optional parameters as discussed here. I've also added in test cases and updated the vignette to describe this new function. Let me know if you have any concerns and then I can merge this into develop.

Thanks!

**Review by anthonysena — APPROVED** [review]

**Pull request merged**
